eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
   service-url:
      defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost  

microservice:
   payment-service:
      endpoints:
         endpoint:
            uri: http://PAYMENT-SERVICE/payment/dopayment11
   order-service:
      endpoints:
         endpoint:
            uri: http://ORDER-SERVICE/order/doOrder

Spring:
   datasource:
      url: jdbc:oracle:thin:@//localhost:1521/xe
      username: SYSTEM
      password: ShlokDada
      driver-class-name: oracle.jdbc.OracleDriver
   jpa:
      show-sql: true
      properties:
         hibernate:
            format_sql: false
            dialect: org.hibernate.dialect.OracleDialect 
      hibernate: 
         ddl-auto: update
            
